# Generated by Django 3.1.5 on 2021-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20210117_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='field_name',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='Watch-this-space.jpg', upload_to='Portfolio/images'),
        ),
    ]
