# Generated by Django 3.1.5 on 2021-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_auto_20210121_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='field_name',
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
